-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Autenticacao"
(
    "E-mail" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Senha" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "TipoUsuario" boolean NOT NULL,
    CONSTRAINT "Autenticacao_pkey" PRIMARY KEY ("E-mail")
);

CREATE TABLE IF NOT EXISTS public."Comprador"
(
    "CPF" character varying(14) COLLATE pg_catalog."default" NOT NULL,
    "Nome" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "E-mail" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "DataNasc" date NOT NULL,
    "Telefone" character varying(14) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Comprador_pkey" PRIMARY KEY ("CPF")
);

CREATE TABLE IF NOT EXISTS public."Corretor"
(
    "CodCorretor" integer NOT NULL DEFAULT nextval('"Corretor_CodCorretor_seq"'::regclass),
    "CPF" character varying(14) COLLATE pg_catalog."default" NOT NULL,
    "Nome" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "E-mail" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Corretor_pkey" PRIMARY KEY ("CodCorretor"),
    CONSTRAINT "CPF" UNIQUE ("CPF")
);

CREATE TABLE IF NOT EXISTS public."Imoveis"
(
    "CodImovel" integer NOT NULL DEFAULT nextval('"Imoveis_CodImovel_seq"'::regclass),
    "CEP" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "Logradouro" character varying(75) COLLATE pg_catalog."default" NOT NULL,
    "Numero" integer NOT NULL,
    "Complemento" character varying(50) COLLATE pg_catalog."default",
    "Bairro" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Cidade" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Estado" character varying(2) COLLATE pg_catalog."default" NOT NULL,
    "Preco" real NOT NULL,
    "ModeloNegocio" boolean NOT NULL,
    "TipoDeImovel" boolean NOT NULL,
    "ImagemImovel" bytea NOT NULL,
    CONSTRAINT "Imoveis_pkey" PRIMARY KEY ("CodImovel")
);

CREATE TABLE IF NOT EXISTS public."Transacao"
(
    "CodTransacao" integer NOT NULL DEFAULT nextval('"Transacao_CodTransacao_seq"'::regclass),
    "CodImovel" integer NOT NULL DEFAULT nextval('"Transacao_CodImovel_seq"'::regclass),
    "CPFComprador" character varying(14) COLLATE pg_catalog."default" NOT NULL,
    "DataHora" date NOT NULL,
    "CodCorretor" integer NOT NULL DEFAULT nextval('"Transacao_CodCorretor_seq"'::regclass),
    CONSTRAINT "CodTransacao" PRIMARY KEY ("CodTransacao")
);

ALTER TABLE IF EXISTS public."Comprador"
    ADD CONSTRAINT "E-mail" FOREIGN KEY ("E-mail")
    REFERENCES public."Autenticacao" ("E-mail") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Corretor"
    ADD CONSTRAINT "E-mail" FOREIGN KEY ("E-mail")
    REFERENCES public."Autenticacao" ("E-mail") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Transacao"
    ADD CONSTRAINT "CPFComprador" FOREIGN KEY ("CPFComprador")
    REFERENCES public."Comprador" ("CPF") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Transacao"
    ADD CONSTRAINT "CodCorretor" FOREIGN KEY ("CodCorretor")
    REFERENCES public."Corretor" ("CodCorretor") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Transacao"
    ADD CONSTRAINT "CodigoImovel" FOREIGN KEY ("CodImovel")
    REFERENCES public."Imoveis" ("CodImovel") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;